### ISSUE TITLE
psxrip creates wrong characters in catalog

### ISSUE THREAD

**Issue by tatref** [cebix/psximager#1]
The original volume_id is "SCUS_94426", after using psxrip, it appears in the catalog as "SCUS-94426"

Output from executable is:

```
./psxrip CTR.cue
Analyzing image "CTR.cue"...
Volume ID = SCUS-94426
...
```

The volume ID comes from iso9660_get_volume_id, so I don't think this is fixable in a nice way.

Also, the copyright_file_id includes slashes (/), when running psxbuild I have:

```
./psxbuild ./output/.cat myCTR
Reading catalog file "./output/.cat"...
Reading filesystem from directory "./output/"...
Illegal character '/' in copyright_file_id "SCEAI/NDI/UIS"
```

Manually changing the copyright_file_id to "SCEAI_NDI_UIS" in the catalog fixes the issue.

Maybe it is possible to replace the bad characters afterwards?

**Comment by fy-iceworld** [comment]
tatref, have you compiled psxbuild successfully? Could publish a compiled exe of psxbuild, which could run on windows?

**Comment by tatref** [comment]
I don't know about Windows, I'll open a pull request with details about requirements on Ubuntu.

**Comment by MrSapps** [comment]
Pushed some win bins here: https://github.com/paulsapps/psximager/releases

**Comment by developedsoftware** [comment]
How did you compile them windows binaries? I am really struggling due to old dependencies.

**Comment by MrSapps** [comment]
can't recall now.. msys or something..

**Comment by cebix** [comment]
psxrip works correctly. The strings are extracted as they are stored in the disc image.
Commit 9c32ba2 downgrades the errors from psxbuild to warnings.
