### ISSUE TITLE
Compiling in Windows with MSYS2/MinGW-w64

### ISSUE THREAD

**Issue by Danfun64** [cebix/psximager#10]
I know you said at one point in time that you don't work with Windows, but I'm hoping that someone reading this is able to fix my problem with attempting to compile a windows build.

http://paste.debian.net/1089119/

My MSYS2/MinGW-w64 configuration is up to date as of this writing.

**Comment by cetygamer** [comment]
@Danfun64, please check out my MR: #11

**Comment by cebix** [comment]
Resolved by 0f1ff12 and 9a75119

**Comment by cetygamer** [comment]
Hi, @cebix, sorry for late response. I verified that tools can be built via instructions in INSTALL. Thank you for the fixes.

**Comment by cebix** [comment]
@cetygamer I've now replaced all the Boost functions with C++20 standard library functions. Can you verify if this still works under Windows?

**Comment by cetygamer** [comment]
@cebix, still ok.
