### ISSUE TITLE
Can't build under Debian 11

### ISSUE THREAD

**Issue by sabudum** [cebix/psximager#14]
this is the output when running "make":

`make
Making all in src
make[1]: Entering directory '/media/thales/Data/Games/Emulation/PSX ISOS/Racing Lagoon/psximager-2.0/src'
g++ -DPACKAGE_NAME=\"PSXImager\" -DPACKAGE_TARNAME=\"psximager\" -DPACKAGE_VERSION=\"2.0\" -DPACKAGE_STRING=\"PSXImager\ 2.0\" -DPACKAGE_BUGREPORT=\"cb@cebix.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"psximager\" -DVERSION=\"2.0\" -I.       -g -O2 -MT psxbuild.o -MD -MP -MF .deps/psxbuild.Tpo -c -o psxbuild.o psxbuild.cpp
psxbuild.cpp:34:10: fatal error: boost/algorithm/string/trim.hpp: No such file or directory
   34 | #include <boost/algorithm/string/trim.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:402: psxbuild.o] Error 1
make[1]: Leaving directory '/media/thales/Data/Games/Emulation/PSX ISOS/Racing Lagoon/psximager-2.0/src'
make: *** [Makefile:360: all-recursive] Error 1
`

**Comment by sabudum** [comment]
Managed to make it see the boost installation, now I'm getting this:

make
Making all in src
make[1]: Entering directory '/media/thales/Data/Games/Emulation/PSX ISOS/Racing Lagoon/psximager-2.0/src'
g++  -g -O2   -o psxbuild psxbuild.o -lcdio -lm -liso9660 -lcdio -lm -lvcdinfo -liso9660 -lcdio -lm -lboost_filesystem -lboost_regex -lboost_system 
g++ -DPACKAGE_NAME=\"PSXImager\" -DPACKAGE_TARNAME=\"psximager\" -DPACKAGE_VERSION=\"2.0\" -DPACKAGE_STRING=\"PSXImager\ 2.0\" -DPACKAGE_BUGREPORT=\"cb@cebix.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"psximager\" -DVERSION=\"2.0\" -DHAVE_BOOST=/\*\*/ -DHAVE_BOOST_FILESYSTEM=/\*\*/ -DHAVE_BOOST_REGEX=/\*\*/ -DHAVE_BOOST_SYSTEM=/\*\*/ -I.       -g -O2 -MT psxinject.o -MD -MP -MF .deps/psxinject.Tpo -c -o psxinject.o psxinject.cpp
mv -f .deps/psxinject.Tpo .deps/psxinject.Po
g++  -g -O2   -o psxinject psxinject.o -lcdio -lm -liso9660 -lcdio -lm -lvcdinfo -liso9660 -lcdio -lm -lboost_filesystem -lboost_regex -lboost_system 
g++ -DPACKAGE_NAME=\"PSXImager\" -DPACKAGE_TARNAME=\"psximager\" -DPACKAGE_VERSION=\"2.0\" -DPACKAGE_STRING=\"PSXImager\ 2.0\" -DPACKAGE_BUGREPORT=\"cb@cebix.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"psximager\" -DVERSION=\"2.0\" -DHAVE_BOOST=/\*\*/ -DHAVE_BOOST_FILESYSTEM=/\*\*/ -DHAVE_BOOST_REGEX=/\*\*/ -DHAVE_BOOST_SYSTEM=/\*\*/ -I.       -g -O2 -MT psxrip.o -MD -MP -MF .deps/psxrip.Tpo -c -o psxrip.o psxrip.cpp
psxrip.cpp: In function ‘void dumpFilesystem(CdIo_t*, std::ofstream&, bool, const boost::filesystem::path&, const string&, const string&, unsigned int)’:
psxrip.cpp:110:75: error: too many arguments to function ‘CdioList_t* iso9660_fs_readdir(CdIo_t*, const char*)’
  110 |  CdioList_t * entries = iso9660_fs_readdir(image, inputPath.c_str(), false);
      |                                                                           ^
In file included from psxrip.cpp:25:
/usr/include/cdio/iso9660.h:1060:14: note: declared here
 1060 | CdioList_t * iso9660_fs_readdir (CdIo_t *p_cdio, const char psz_path[]);
      |              ^~~~~~~~~~~~~~~~~~
psxrip.cpp:230:31: error: too few arguments to function ‘void _cdio_list_free(CdioList_t*, int, CdioDataFree_t)’
  230 |  _cdio_list_free(entries, true);
      |                               ^
In file included from /usr/include/cdio/iso9660.h:40,
                 from psxrip.cpp:25:
/usr/include/cdio/ds.h:46:6: note: declared here
   46 | void _cdio_list_free (CdioList_t *p_list, int free_data, CdioDataFree_t free_fn);
      |      ^~~~~~~~~~~~~~~
psxrip.cpp: In function ‘void dumpLBNTable(CdIo_t*, const string&, std::ostream&)’:
psxrip.cpp:300:75: error: too many arguments to function ‘CdioList_t* iso9660_fs_readdir(CdIo_t*, const char*)’
  300 |  CdioList_t * entries = iso9660_fs_readdir(image, inputPath.c_str(), false);
      |                                                                           ^
In file included from psxrip.cpp:25:
/usr/include/cdio/iso9660.h:1060:14: note: declared here
 1060 | CdioList_t * iso9660_fs_readdir (CdIo_t *p_cdio, const char psz_path[]);
      |              ^~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:402: psxrip.o] Error 1
make[1]: Leaving directory '/media/thales/Data/Games/Emulation/PSX ISOS/Racing Lagoon/psximager-2.0/src'
make: *** [Makefile:360: all-recursive] Error 1

**Comment by sabudum** [comment]
If I try to run psxbuild:
./psxbuild
./psxbuild: error while loading shared libraries: libboost_filesystem.so.1.82.0: cannot open shared object file: No such file or directory


If I try to run psxinject:
./psxinject
./psxinject: error while loading shared libraries: libboost_filesystem.so.1.82.0: cannot open shared object file: No such file or directory

**Comment by cebix** [comment]
The dependency on Boost has been removed, so this should be resolved.
