### ISSUE TITLE
Hello, could you publish a compiled exe of psxbuild?

### ISSUE THREAD

**Issue by fy-iceworld** [cebix/psximager#3]
Hello, I'd like to ask could you publish a compiled exe of psxbuild, which could run on windows?
I don't know how to compile it right now anyway.

**Comment by cebix** [comment]
I'm sorry, I don't have Windows.

**Comment by fy-iceworld** [comment]
I‘m glad you replied. Then do you have a compiled psxbuild which could run on Linux? I have Linux on my computer at home.

**Comment by MrSapps** [comment]
https://github.com/paulsapps/psximager/releases/tag/v2.0_bins

I've pushed some binaries here, building on windows is a bit of a pain!

**Comment by fy-iceworld** [comment]
Nice work, can I run it on Windows?

**Comment by MrSapps** [comment]
Yes that is the idea ;)

**Comment by fy-iceworld** [comment]
Great achievments!
