### ISSUE TITLE
psxrip on macOS (builds but does not run correctly)

### ISSUE THREAD

**Issue by gingerbeardman** [cebix/psximager#7]
Builds thanks to this fork && branch:
https://github.com/edmeme/psximager/tree/patch-libcdio-2.0.0-1

Still some issues with that version as psxrip isn't running quite right.

Help, please?

**Comment by cebix** [comment]
Can you describe more precisely what isn't "quite right"? Error messages? Expected vs. actual output?

**Comment by gingerbeardman** [comment]
Sadly after 6 years I cannot recall, and the fork I used to build is dead.

I'm sorry I wasn't more specific when I filed the issue.

I just tried and am unable to build for macOS, and that is still the goal.

**Comment by cebix** [comment]
I guess I can close this, then.

**Comment by gingerbeardman** [comment]
I found reference in the other thread you just closed @cebix  https://github.com/cebix/psximager/issues/2#issuecomment-406097228

It seems I could get it to build but I could not get it to produce correct output.

I guess you'll need a modern Mac to resolve this.
